### ISSUE TITLE
Libraries specific verions.

### ISSUE THREAD

**Issue by RanulfoBezerra** [EpiSci/SoCRATES#1]
Thank you for your work!
I have read your paper and decided to test the results, but it seems that the Gym version used on this project is not the most recent one.
The new version requires:
`self.action_space 
 self.observation_space `
 Since I could not find this the following errors occur:
`AssertionError: The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/
`
 `AssertionError: The environment must specify an observation space. https://www.gymlibrary.dev/content/environment_creation/
`
On running the:
`python run_heuristic_scheduler.py `

Could you please provide the versions of the libraries that you are using to reproduce your results?

**Comment by teggme** [comment]
Hi, I used `gym==0.21.0`. Please let me know if you have any further questions.

**Comment by RanulfoBezerra** [comment]
hello @teggme 
Thank you for your quick reply!
Unfortunately I could not run any of the algorithms. It seems that it needs some specific libraries.
For example when trying to run:
`python run_heuristic_scheduler.py`
I get the following error:
`   self.env.reset(args)
TypeError: reset() takes 1 positional argument but 2 were given`
When trying to run:
`python run_deepsocs_scheduler.py `
I get the following error:
`ModuleNotFoundError: No module named 'aiohttp.signals'`
Even after installing the module, it gives a different error related to the version of the instalation which I think the best would be:
`aiosignal                 1.2.0 `
Could you provide a list of the packages that you have installed on your conda environment to run this code?

**Comment by teggme** [comment]
> `self.env.reset(args) TypeError: reset() takes 1 positional argument but 2 were given`

Could you add an input argument specifically and run again? `self.env.reset(args=args)`

> `python run_deepsocs_scheduler.py` I get the following error: `ModuleNotFoundError: No module named 'aiohttp.signals'`

In order to run DeepSoCS you have to install TensorFlow.

A list of library versions that I used are as follows.
```
networkx==2.5.1
matplotlib==3.3.4
simpy==4.0.1
gym==0.21.0
pandas==1.1.5
ray==1.12.0
torch-cluster==1.5.9
torch-scatter==2.0.9
torch-sparse==0.6.12
torch-spline-conv==1.2.1
torch-geometric==2.0.3
wandb==0.12.15
seaborn==0.11.2
scipy==1.5.4
scikit-learn==0.24.2
tensorflow
```

**Comment by RanulfoBezerra** [comment]
@teggme 
Thank you very much for your reply!!

> Could you add an input argument specifically and run again? `self.env.reset(args=args)`

After changing this I am able to run the heuristics!!
However for the `python run_deepsocs_scheduler.py` I get the following error:
`Traceback (most recent call last):
  File "run_deepsocs_scheduler.py", line 28, in <module>
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'`
I believe this is due the tensorflow that you used is around version 1.x.x, and I am using tensorflow 2.6.2
Could you specify which tensorflow version did you use?

**Comment by teggme** [comment]
Sorry for the late reply. I use tensorflow with version 1.15, but you will get some other errors. Regarding DeepSoCS scheduler, I have some code changes to be updated.
Other than DeepSoCS, are you able to run SoCRATES scheduler?

**Comment by RanulfoBezerra** [comment]
@teggme 
When I try to run the socrates scheduller I think there is a error with the pytorch, my GPU drivers are installed, and cuda toolkit too, but still this error shows up:
`File "/opt/conda/envs/socrates2/lib/python3.6/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available`

But related to the deepsocs, I was able to make it work on tensorflow 2.6.2 by changing the code from tf1 to tf2, and disabling the eager execution.
`tf.compat.v1.disable_eager_execution()`

**Comment by teggme** [comment]
Actually, I trained SoCRATES without GPU, and it won't take much time. Can you disable GPU and run SoCRATES?

**Comment by RanulfoBezerra** [comment]
@teggme 
Without GPU it works!
Do you have any tips for it to work with GPU?

**Comment by teggme** [comment]
I haven't planned to develop GPU-enabled codes since the training without GPU takes not much time. It depends on the scenario of job/resource profiles, but we think training the agent with CPU is enough since the network structure is not much deep.
